name: Deploy site

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy site to AWS S3
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.S3_BUCKET_REGION }}

    - name: Build
      run: mkdir dist/ && cp -a assets/ index.html dist/ && test -d dist/

    - name: Deploy
      uses: reggionick/s3-deploy@v3
      with:
        folder: ${{ secrets.S3_FOLDER }}
        bucket: ${{ secrets.S3_BUCKET }}
        bucket-region: ${{ secrets.S3_BUCKET_REGION }}
        dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        invalidation: /
        delete-removed: true
        no-cache: true
        private: true
